# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
